### ISSUE TITLE
Refactor to execute migration earlier

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-liquibase#1]
Enabling Hibernate to validate the schema makes the migration fails because the validation is executed before the migrations are executed.

It can be reproduced with this configuration:

```
datasources:
    default:
        url: 'jdbc:mysql://localhost:3306/micronaut_liquibase'
        username: root
        password: pass
        driverClassName: com.mysql.cj.jdbc.Driver
jpa:
    default:
        packages-to-scan:
            - 'foo.bar'
        properties:
            hibernate:
                hbm2ddl:
                    auto: validate # <--- 'validate' instead of 'none'
                show_sql: false
liquibase:
    datasources:
        default:
            change-log: classpath:db/liquibase-changelog.xml
```
