### ISSUE TITLE
Liquibase doesn't seem to run with a hibernate gorm datasource

### ISSUE THREAD

**Issue by jisikoff** [micronaut-projects/micronaut-liquibase#18]
With a hibernate gorm setup in micronaut like this:
```
dataSource:
  url: ...
  pooled: true
  jmxExport: true
  driverClassName: 
  username:
  password: 

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog-master.groovy'
```

the liquibase runner seems to not run because it doesn't get past this line in LiquibaseMigrationRunner:
```
     if (event.getBeanDefinition() instanceof NameResolver) {
```
