### ISSUE TITLE
Allow hibernate schema validation after migration

### ISSUE THREAD

**Issue by TimothyL96** [micronaut-projects/micronaut-liquibase#250]
```
dataSource:
  url: jdbc:mysql://...
  driverClassName: com.mysql.cj.jdbc.Driver
  username: 
  password: 

hibernate:
  hbm2ddl:
    auto: validate
```

With **Micronaut Hibernate GORM**, configuring **hbm2ddl** to **validate** will cause startup to fail if schema is invalid.

<br/>
I think is useful if we can enable validation and liquibase will run the migration before the validation and not after.

I found a similar ticket but I guess this is not for GORM? [https://github.com/micronaut-projects/micronaut-liquibase/issues/1]

<br>
The current workaround will be to retrieve the Hibernate metadata from GORM and run the schema validator manually.

```
class ValidatorService
{
	@Inject
	HibernateDatastore hibernateDatastore
	
	void validate()
	{
                // retrieve existing metadata
                def metadata = hibernateDatastore.getMetadata()

                // throw exception on failed validation
		new SchemaValidator().validate(metadata)
	}
}
```
and then call the **validate()** on startup with something like a startup listener:
```
void onApplicationEvent(StartupEvent event)
{
    validator.validate()
}
```
