### ISSUE TITLE
Stop the service

### ISSUE THREAD

**Issue by albertogoffi** [micronaut-projects/micronaut-liquibase#3]
Hi all,

I'm working on a project where:

- Liquibase migrations run during service startup;
- service startup should fail (i.e., the service should terminate) if the Liquibase migration process fails.

With the current Micronaut-Liquibase integration when a Liquibase migration fails an error is logged. However, the service continues to be up & running.

How can I let the service stop when a Liquibase migration fails?
As a general consideration, why the current micronaut-liquibase integration has been develop with such default behavior? Wouldn't be better to stop the service if the Liquibase migration fails?

I'm using the following configuration:
```yml
datasources:
  default:
    platform: postgresql
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: 1234

datasources:
  default:
    change-log: classpath:liquibase/db-changelog.yml
```
